version: "3"

services:

  generic-repo-pattern-demo-postgres:
    image: debezium/postgres:15-alpine
    environment:
      - POSTGRES_DATABASE=generic_repo_pattern_demo
      - POSTGRES_USER=...
      - POSTGRES_PASSWORD=...
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db

  server:
    image: genericrepopatterndemo
    ports:
      - "5000:80"

volumes:
  postgres-data:
